spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chidtw09@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url : jdbc:mysql://127.0.0.1:3306/HTTinhTienNuoc
    username : root
    password :
    driver-class-name : com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
ftp:
  host: 192.168.0.101
  port: 21
  username: ftp-user
  password: 123456789
